'\" t
.\"     Title: unlink
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2012
.\"    Manual: User Commands
.\"    Source: System Manager's Manual
.\"  Language: English
.\"
.TH "UNLINK" "1" "09/08/2012" "System Manager's Manual" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
unlink \- remove a directory entry
.SH "SYNOPSIS"
.HP \w'\fBunlink\fR\ 'u
\fBunlink\fR \fBfile\fR
.SH "DESCRIPTION"
.PP
The
\fBunlink\fR
command removes a directory entry, specified as
\fBfile\fR\&. If the directory entry cannot be removed for any reason, a diagnostic message is printed\&.
.SH "OPERANDS"
.PP
\fBfile\fR
.RS 4
The pathname of a directory entry which is to be removed\&.
.RE
.SH "DIAGNOSTICS"
.PP
The following error values are returned:
.\" line length increase to cope w/ tbl weirdness
.ll +(\n(LLu * 62u / 100u)
.TS
ll.
\fIError value\fR	\fIDiagnostic\fR
T{
\fB0\fR
T}	T{
Successful completion\&.
T}
T{
\fB>0\fR
T}	T{
An error occurred\&.
T}
.TE
.\" line length decrease back to previous value
.ll -(\n(LLu * 62u / 100u)
.sp
.SH "NOTE"
.PP
On many systems, the
\fBunlink\fR
command cannot be used to remove directories\&.
.SH "STANDARDS"
.PP
The
\fBlink\fR
utility conforms to the
Single UNIX Specification, Version 3 (SUSv3), and the
X/Open System Interfaces Extension (XSI)\&.
.SH "SEE ALSO"
.PP

\fBrm\fR(1),
\fBrmdir\fR(1),
\fBlink\fR(1),
\fBunlink\fR(2)\&.
